---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCSjf72XIQ46Tu+9beO4mBXL9r8lx1ky/Rzwpq+WABvGQbRGYSgmA2F9T8eVWFy32t5rNwHNU0oZ7IuEqxievggbooOgJARfNVogmXhkJqlEiZqqr+bOYR+HbCrK3BMut4lCPCb9LHPmnkIztOpQM9yZ1SdtucW9tAjpHrONXuc1GUQEfBbA1PsdMREwfQ/rRlcZK4qDB5Qe4XAiQbxTh9hr9zLMMB5zsZsOXwA3C4MVEcLDQk+ubp/1hiZX/dZCaYuZb8uYPbCv3/5XFLSND3yozgmEUUF6IdJAixfkjq73Pn+uLWw0kqNc1YelVaDuS69m2uSi88lcXZzy2eQwv/Mf+/gBWU6LxcNd+2vk4CwQDYJXvUZP+HpxevR0yDi7/b2Bk1Rc/sY+I6/TRLip8rm8WPXeOAme4Uet4R5m/PlUMYJhvOVj/1O8DlKr+6F3RDD24mWzMinGvcT8JLlVkaslHfqmC06IfJzUJiZSNWKmpjL1vPDR12FbU0wW1/bFgZLTkooMe+Rk35EkTppMA4EhdN4FE0R6kX0rJlaKv5I8NVEXrSpBQznl32+/ToAQ6pS0UOx84yFwygAQXVNCcMAXqe+KY7CWeFVaCAfmdDs/0A5ABmYhMvgfYarmCjdmcCu/lwoseCC5m/gVNVIzTp6NO6bq27mNWycVyYMT/8AwIqDSSbWqdcXJcuLitCV2aLjKFAewZfPGD3LY9NEUP0E4w==
    client_secret: AgDLdn6tnDNbbj2+PCjKo+dLrz/Pg9ptCn0Dxk48lktNKpSu9hXolKpuXXSUh6t8FEOCLyGN5lUlg9Kaduc6LqtRse7OUAnyQ0aCGy3sH7BwF4n7RXJzy88hyoueaYaJcgHGMJrqbilJG07QkcF/Q1xsCP+OOXtP18U+Mf4Ug9Uj8CnyVeH1cg1LegYJt3/utEJM3GM4XqKLgWCqWslMDlqXHPUbMUq8owtd7yzOoh8iv2aDAoePYtnBu5EclckF4bg1LJRd1g80vWUFMkW7dfSL5AYNMbD5UsX3qb9BpklMt1RxCaNGBCxrpPndCZvScUkU2rt+5s2wGLXyRMHMDZrbLCLpBSZgYsbuUjHlkkGzvSvN9qG81CgxbDxUKq2Cpef3VzmoBoY3DY2b3jqjtDf5BdDGlwOvYIxdWRlIXiApd6xE+eoffW5Tqfc14F7HZ7i0icLPqhLFDKu8bGD0pEh5e9M3iBGr/j2W0tq34tx2s0ZPoC80mgPXdJfXmfnUvur6fRgppDr98yP8cEACWhSmwLRwgTTqi17PqDF0dM/rCscvA42/g0EHFUUWLVveHvQZSuuvIRbmV6Q5R/y0/k0P1qdg+fyNV7wGO48FuyKxyEz84IwwFvEfX17iWmaatMSmF53CslNXCFnKolQYuewhsSioTkUe3IZBK8IiZvXL0L07fXw48EeFML0qt0I8hUPuvkMIcruFGqlMdoHEpWSDF4Si8QLw1SXYddfWhFK1vaunFO94LE6tAXSt76a15drq7snlDr49z9qvjaNOsCVn
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
