apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-rollouts-tailscale
  namespace: argo-rollouts
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - rollouts
  rules:
    - host: rollouts
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-rollouts-dashboard
                port:
                  number: 3100
