---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: miniflux-admin
  namespace: miniflux
spec:
  encryptedData:
    ADMIN_PASSWORD: AgCPRCft7HXKpzkWT4+sNCyhjTcVQGLsHskx/aOKMd/uM7OdUXYmRLxPy9l8KM2dOPtekemX2u7zLJdIl/pw64NYf0OMjLdjN5U792DaK5DRX9+dNd4YHr/JQrPbvSdNH34Gb902WIH9N0CsxIoRq6aSshn+u2pnkxA+sW1wgb+TNsA53vqfOmHL9xiRBgABBZbNXIJs5AWLOSJNMLlPJP3U+mCVtoz2lHCR+nPtjFqDqQ114jyo3MHuUmaWqHU0BbYyub6cVAS8isaGdWzAI0om1zANXN1p3Q+XRqSgA399mTyuyW2GF45t9cdJOy5E/duyOhODFadRoQ5y6ynH4usIqZVGSXjJC+BVYSwHsb2uOcjYj4EG3RLAfEjhz9ubSUIbw7YEUm1cJ2REmYeBdL7/5UPk/MZe94b0NQC6rl10r6vP2yrvzWKnxJMjkb1fM/5jy4/als7zW+EkKOmKDECMTX7D7jei3svinCHPm6ECdG23b7OiJVEZs43Yr00QEh9m9QDcP5l7nRgUw2vmB9FnTKz2TUF1vRDY0/O0AOEKFjUTnIjJ6OeVkFIvkrDaeHHFci3leEY5ji3c4wdCMImDNTBr6zWwuTvdpjc8r/RPTv5jECztTowLHsgT1m0YpVLpQdmyP9PslL2L1laYYmqpyrdBjsJGWwI+KaDMusopY8gJfH+OUFmj9fYFrauKC25dqj4f7ft95/nh
    ADMIN_USERNAME: AgDZu2J+GsxMAV2aqYggx2917MKpLy/yZSfEm8bfDmNGOm027XUGjmw5TMdWsgmMOqPA1L2vxtHXP/axHSP4y6J2dJK8/TavWtEQdh+2RzXRAb9Lg6un9NdxPrsFUJ3V+HnIwxNknl08flcMSsVxAFUwwQaC3fnAWKauPSms04ZTQMMmJ+c/4MwJtvJ+QqpRGcuSPxmQ5nyk90iOINpTuUjBP73h4qZrZdd47gGfPArCIxf7P5rNxoPKlahU+G/lUYZQN7F4uEYi983vOcn3H8kELZpdyF+0IYPmc+lHUwVhWygCwzWRgDTqiZSxH+2VYmveRnASPPHYbgF1SVIw8l1+ieZd7mP0mOkAz+msAe0ER478ulELH5KCCA3m2Zg9dL7/OVjbHDiRltjRWKcY4M2lPzHXF+yBTx+3dSbHybCbVmoxiIW3//ZOyxC5HPczbyIRA3J+vip/nLLkrZUM+NDffrg1RQL50X06ERFuLrFwoL+FWZW6qdb30GfEHwbTW9UDS6lpz/B1KljMOe+toFsWqAF/AOAHvuZTKRNQM31t67m3g3wSic4GPpCr+eaUbLXQnQI9uTzs6MQpkOLFB3xGWEniHffgPgeZJ6BdLnyeEuKSMm2oCj7jfSu/MZ9+vrnHJeOKmSXMimrJ4zpXyYv36wk8IeXwnW/uWMHK/zZ/b9oI2/+44YvBDcN/fSAssIIMLThXAw==
  template:
    metadata:
      name: miniflux-admin
      namespace: miniflux
