apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbelMeijberg/homelab-cluster.git
    targetRevision: main
    path: apps/rollout-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: rollout-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
